package no.nav.medlemskap.saga.domain

data class VurderingForAnalyseUttrekk(
    val dato: String,
    val ytelse: String,
    val fom: String,
    val tom: String,
    val førsteDagForYtelse: String,
    val startDatoForYtelse: String,
    val svar: String,
    val årsaker: String,
    val konklusjon: String,
    val avklaringsListe: String,
    val nyeSpørsmål: String,
    val antallDagerMedSykmelding: String,
    val statsborgerskap: String,
    val statsborgerskapskategori: String,
    val arbeidUtenforNorge: String,
    val utførtArbeidUtenforNorge: String,
    val utførtArbeidUtenforNorgeLand: String,
    val utførtArbeidUtenforNorgeFom: String,
    val utførtArbeidUtenforNorgeTom: String,
    val utførtArbeidUtenforNorgeAntallPerioder: String,
    val oppholdUtenforEØS: String,
    val oppholdUtenforEØSLand: String,
    val oppholdUtenforEØSFom: String,
    val oppholdUtenforEØSTom: String,
    val oppholdUtenforEØSAntallPerioder: String,
    val oppholdUtenforEØSGrunn: String,
    val oppholdUtenforNorge: String,
    val oppholdUtenforNorgeLand: String,
    val oppholdUtenforNorgeFom: String,
    val oppholdUtenforNorgeTom: String,
    val oppholdUtenforNorgeAntallPerioder: String,
    val oppholdUtenforNorgeGrunn: String,
    val oppholdstillatelseOppgitt: String,
    val oppholdstillatelseOppgittFom: String,
    val oppholdstillatelseOppgittTom: String,
    val oppholdstillatelseOppgittAntallPerioder: String,
    val oppholdstillatelseUDIFom: String,
    val oppholdstillatelseUDITom: String,
    val oppholdstillatelseUDIType: String,
    val kilde: String
)

fun VurderingForAnalyseUttrekk.tilListe(): List<String> = listOf(
    dato,
    ytelse,
    fom,
    tom,
    førsteDagForYtelse,
    startDatoForYtelse,
    svar,
    årsaker,
    konklusjon,
    avklaringsListe,
    nyeSpørsmål,
    antallDagerMedSykmelding,
    statsborgerskap,
    statsborgerskapskategori,
    arbeidUtenforNorge,
    utførtArbeidUtenforNorge,
    utførtArbeidUtenforNorgeLand,
    utførtArbeidUtenforNorgeFom,
    utførtArbeidUtenforNorgeTom,
    utførtArbeidUtenforNorgeAntallPerioder,
    oppholdUtenforEØS,
    oppholdUtenforEØSLand,
    oppholdUtenforEØSFom,
    oppholdUtenforEØSTom,
    oppholdUtenforEØSAntallPerioder,
    oppholdUtenforEØSGrunn,
    oppholdUtenforNorge,
    oppholdUtenforNorgeLand,
    oppholdUtenforNorgeFom,
    oppholdUtenforNorgeTom,
    oppholdUtenforNorgeAntallPerioder,
    oppholdUtenforNorgeGrunn,
    oppholdstillatelseOppgitt,
    oppholdstillatelseOppgittFom,
    oppholdstillatelseOppgittTom,
    oppholdstillatelseOppgittAntallPerioder,
    oppholdstillatelseUDIFom,
    oppholdstillatelseUDITom,
    oppholdstillatelseUDIType,
    kilde
)

