package no.nav.medlemskap.saga.domain

import no.nav.medlemskap.saga.domain.datagrunnlag.Ytelse
import no.nav.medlemskap.saga.domain.konklusjon.Statsborgerskapskategori
import java.time.LocalDate

data class VurderingForAnalyse(
    val ytelse: Ytelse,
    val fom: LocalDate,
    val tom: LocalDate,
    val fnr: String,
    val førsteDagForYtelse: LocalDate,
    val startDatoForYtelse: LocalDate,
    val svar: Svar,
    val årsaker: List<String>,
    val konklusjon: Svar,
    val avklaringsListe: List<String>,
    val nyeSpørsmål: Boolean,
    val antallDagerMedSykmelding: Long,
    val statsborgerskap: List<String>,
    val statsborgerskapskategori: Statsborgerskapskategori,
    val arbeidUtenforNorge: Boolean,
    val utførtArbeidUtenforNorge: Boolean,
    val utførtArbeidUtenforNorgeLand: String,
    val utførtArbeidUtenforNorgeFom: String,
    val utførtArbeidUtenforNorgeTom: String,
    val utførtArbeidUtenforNorgeAntallPerioder: Int,
    val oppholdUtenforEØS: Boolean,
    val oppholdUtenforEØSLand: String,
    val oppholdUtenforEØSFom: String,
    val oppholdUtenforEØSTom: String,
    val oppholdUtenforEØSAntallPerioder: Int,
    val oppholdUtenforEØSGrunn: String,
    val oppholdUtenforNorge: Boolean,
    val oppholdUtenforNorgeLand: String,
    val oppholdUtenforNorgeFom: String,
    val oppholdUtenforNorgeTom: String,
    val oppholdUtenforNorgeAntallPerioder: Int,
    val oppholdUtenforNorgeGrunn: String,
    val oppholdstillatelseOppgitt: Boolean,
    val oppholdstillatelseOppgittFom: String,
    val oppholdstillatelseOppgittTom: String,
    val oppholdstillatelseOppgittAntallPerioder: Int,
    val oppholdTillatelseUDIFom: String,
    val oppholdTillatelseUDITom: String,
    val oppholdTillatelseUDIType: String,
)