apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-saga
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: medlemskap
            envVarPrefix: DB
            tier: db-g1-small
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: "dec3ee50-b683-4644-9507-520e8f054ac2" #rolle jeg vet test bruker i dev har
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a"
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
          - id: "c811e9f4-26a6-43f9-b930-8c83365683a9"
          - id: "59f26eef-0a4f-4038-bf46-3a5b2f252155"
          - id: "317665ad-1402-458e-b8e6-9cb50afc1252" # speil-brukere-dev
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://medlemskap-vurdering.intern.dev.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  secureLogs:
    enabled: true
  webproxy: true
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: medlemskap-sykepenger-listener
        - application: letme-lovme
          namespace: medlemskap
          cluster: dev-gcp
        - application: sparkel-medlemskap
          namespace: tbd
          cluster: dev-fss
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      external:
        - host: api-gw-q1.oera.no
        - host: api-gw-q2.oera.no
        - host: saf.dev-fss-pub.nais.io
        - host: login.microsoftonline.com
  env:
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw-q1.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
