apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-saga
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: db-g1-small
        databases:
          - name: medlemskap
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://medlemskap-vurdering.intern.dev.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  webproxy: true
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: medlemskap-analyse
        - application: medlemskap-sykepenger-listener
        - application: letme-lovme
          namespace: medlemskap
          cluster: dev-gcp
        - application: sparkel-medlemskap
          namespace: tbd
          cluster: dev-fss
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      external:
        - host: api-gw-q1.oera.no
        - host: api-gw-q2.oera.no
        - host: saf.dev-fss-pub.nais.io
        - host: login.microsoftonline.com
      rules:
        - application: logging
          namespace: nais-system
  env:
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw-q1.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
