CREATE TABLE vurdering_analyse (
    id                                  SERIAL PRIMARY KEY,
    dato                                DATE,
    ytelse                              TEXT,
    fom                                 DATE,
    tom                                 DATE,
    fnr                                 TEXT,
    foersteDagForYtelse                 DATE,
    startDatoForYtelse                  DATE,
    svar                                TEXT,
    aarsaker                            TEXT[],
    konklusjon                          TEXT,
    avklaringsliste                     TEXT[],
    nyeSpoersmaal                       BOOLEAN,
    antallDagerMedSykmelding            INT,
    statsborgerskap                     TEXT[],
    statsborgerskapskategori            TEXT,
    arbeidUtenforNorge                  BOOLEAN,
    utfoertArbeidUtenforNorgeTag        JSONB,
    oppholdUtenforEOSTag                JSONB,
    oppholdUtenforNorgeTag              JSONB,
    oppholdstillatelseOppgittTag        JSONB,
    oppholdstillatelseUDIFom            DATE,
    oppholdstillatelseUDITom            DATE,
    oppholdstillatelseUDIType           TEXT,
);