name: Vulnerabilities scanning of dependencies
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: monitor
          args: --file=build.gradle.kts --configuration-attributes=usage:java-runtime --org=medlemskap --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git
